# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbfeaf2e8c9c380b1a37528df1199468c5c9ae14907b54e75db71fd6719bda0d1a09678801d45d5e5133e4b67ecad76f8dcaf09a941e02fe50d81ea44e188060

test:
  secret_key_base: b8c1963def4525e77e9a7dc54fca1fd0fc69d02027f45f49dc50e3ea1f2444f13494d3c7739394c3b6bbc33145df75732d9adb6020e4478c3da92b6a9b747dff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
